language: cpp
compiler:
  - gcc
os:
  - linux
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" ; fi
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgtest-dev libboost-filesystem-dev libboost-system-dev
  - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
script: "scons test"
after_script:
  - "cat config.log"
